language: perl
perl:
  - "5.16"

sudo: required

env:
  - PLACK_ENV=travis

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libdb-dev
  ## Set a git identity
  - git config --global user.email "travis@example.com"
  - git config --global user.name "Travis PAUSE"
  - sudo cp /etc/mysql/my.cnf /usr/share/mysql/my-default.cnf
